FROM node:20-alpine

WORKDIR /app

COPY package*.json ./

RUN npm install

# Don't copy the entire context, only the necessary files if wanted
# Because we are bind the directory to the host machine
# COPY . .

# Copy the Prisma schema (needed for `prisma generate`)
COPY prisma ./prisma

# Generate the Prisma client during image build
RUN npx prisma generate

EXPOSE 5001

CMD ["sh", "-c", "npx prisma generate && npm run dev"]
